### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tomgallagher** [tobyhinloopen/bonaroo-able#4]
Hey Toby

I’ve been reading your excellent [article](https://dev.to/charperbonaroo/creating-a-ts-written-npm-package-for-use-in-node-js-or-browser-5gm3) 

You’ve helped me build my first NPM package. I think this would have taken me forever to learn without your help!

I’ve got quite a basic code package and all the tests pass, the test-build.js passes, etc. It’s got mirrors of all the tests that you used

Then it works in Node and it also works in the browser, using unpkg.com.

However, I cannot work out why the only function on the namespace is not recognised in a webpack environment. Just get an empty object returned.

The main difference in my project is that in the equivalent to your `Able` namespace file, I am importing another function from a file in a folder structure one level down from the `Index` and `Able` files.
 
So like this:

  ```
import { transcodeImage } from './handlers/imageHandler';
  export namespace Transcoded {
    export function imageSrc(url: string, id: string, options: object = {}): string {
        return transcodeImage(url, id, options);
    }
}
```

Any ideas why the empty object might be happening? I can give you the link to the Github repo if you think you might be able to help

Thanks for your time 

Tom

**Comment by tobyhinloopen** [comment]
I just now read your message, sorry for the late reply. Do you still need help with the issue?

**Comment by tomgallagher** [comment]
Thanks for getting back.

No help needed any more. There were clearly issues that I never quite sorted out with regard to the 2nd level of imports into the equivalent of the `Able` file. 

In the end I discovered @pikapack and I outsourced all these problems to them :)

Good weekend and, again, really helpful article.
